[pytest]
testpaths = tests
pythonpath = src src/cyberstartup src/cyberstartup/models
filterwarnings =
    ignore:.*SwigPyPacked.*:DeprecationWarning
    ignore:.*SwigPyObject.*:DeprecationWarning
    ignore:.*swigvarlink.*:DeprecationWarning
    ignore:.*Implicit None on return values is deprecated.*:DeprecationWarning